* DONE Make refresh period configurable
* DONE Make support for timeouts
  Now all plugins are called every time while status
  refresh. Sometimes this is quite insane. F.e. we don't need to
  update time plugin more than one time per second. Even more: if user
  chooses another time format, that doesn't show seconds, it could
  even be called only every minute. So we need some kind of
  caching-expiration mechanism to decrease irrational CPU consuming.

* TODO Build debian package with i3s
* TODO Add i3s to suggests of i3wm debian package
* DONE Fix ram plugin for systems without swap
  I found that without swap "free" tool has a different format. I need
  to use /proc or /sys to get appropriate values of memory.
* TODO Move plugin configuration variables out of functions
* TODO Update default config with all plugin configuration variables
* TODO Add local plugin directory support
* TODO Add separate configuration files for plugins
  It will be needed if I want to split plugins into different packages
